// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBja0j79Mrdqk_S1UxyDcGQHERxQTxsKVs',
    appId: '1:620908408525:web:42858b8a4befcc7844c384',
    messagingSenderId: '620908408525',
    projectId: 'orthodox-bible-1bbfc',
    authDomain: 'orthodox-bible-1bbfc.firebaseapp.com',
    databaseURL: 'https://orthodox-bible-1bbfc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'orthodox-bible-1bbfc.appspot.com',
    measurementId: 'G-LS9844F3YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVhjO2ehl7L1WifOXihUdR53pxj-VJqZE',
    appId: '1:620908408525:android:e0ba14062b79656144c384',
    messagingSenderId: '620908408525',
    projectId: 'orthodox-bible-1bbfc',
    databaseURL: 'https://orthodox-bible-1bbfc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'orthodox-bible-1bbfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNrX_CrP1-hnvYN0hhEWBWCZckrWZf0XA',
    appId: '1:620908408525:ios:5815032096c10a8044c384',
    messagingSenderId: '620908408525',
    projectId: 'orthodox-bible-1bbfc',
    databaseURL: 'https://orthodox-bible-1bbfc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'orthodox-bible-1bbfc.appspot.com',
    iosBundleId: 'bulgarian.orthodox.bible',
  );
}
